# Q1. Create a Null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


# Q2. Create a vector with values ranging from 10 to 49.

In [2]:
b=np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Q3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
c = np.arange(9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Q4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
s=np.array([1,2,0,0,4,0])
print("Original array is: ",s)
non_zero=np.nonzero(s)
print("Indices of non-zero elements are: ",non_zero)

Original array is:  [1 2 0 0 4 0]
Indices of non-zero elements are:  (array([0, 1, 4], dtype=int64),)


# Q5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
b = np.random.rand(10,10)
print("Original Array : \n", b)
bmin, bmax = b.min(), b.max()
print("\n Minimum Value : " ,bmin,)
print("\n Maximum Value : " ,bmax,)

Original Array : 
 [[0.97496678 0.91444233 0.19798279 0.13617822 0.83345693 0.35600268
  0.26274246 0.29982706 0.09069126 0.84664223]
 [0.27900851 0.03087741 0.77398079 0.66305834 0.86546138 0.97547051
  0.69825303 0.09347046 0.19655154 0.02744368]
 [0.19546554 0.84039642 0.36548987 0.72847835 0.72942686 0.14939285
  0.95624362 0.37891645 0.5844361  0.52945973]
 [0.37393124 0.59811105 0.06098292 0.48777141 0.42153258 0.71304705
  0.40419984 0.68054063 0.11025207 0.71301754]
 [0.8811933  0.48450293 0.7911143  0.33368433 0.3736019  0.27348359
  0.57099935 0.31810927 0.87109383 0.28181488]
 [0.59799397 0.64293944 0.90579325 0.5804387  0.55882871 0.62523646
  0.00432967 0.92599426 0.86240362 0.40836841]
 [0.48822882 0.68138518 0.79719795 0.72002764 0.15265408 0.25981414
  0.60003694 0.63897567 0.79631458 0.59983239]
 [0.46999458 0.57030743 0.36130057 0.53839899 0.29059394 0.03306557
  0.6884738  0.36218936 0.59571271 0.58029462]
 [0.51248859 0.0691438  0.10735253 0.79767757 0.29574825 0.66

# Q6. Create a random vector of size 30 and find the mean value.

In [6]:
c = np.random.rand(30)
print("Original array : \n", c)
print("Mean Value : \n", np.mean(c))

Original array : 
 [0.77660127 0.26556604 0.71050145 0.80388019 0.10642111 0.60598241
 0.49771901 0.02718544 0.32246293 0.10927054 0.98886592 0.00613564
 0.10183604 0.68257673 0.81028055 0.96766473 0.46886034 0.43404699
 0.73296823 0.95926143 0.91289694 0.9232625  0.05688367 0.56611708
 0.34559649 0.99180354 0.87345982 0.33536736 0.03940834 0.93406184]
Mean Value : 
 0.5452314863381172
